version: '3'

volumes:
  mysql-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    name: ${PROJECT_NAME}-network

services:
  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - network-id

  php:
    image: php:7.4-apache
    container_name: ${PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html
    links:
      - mysql
    networks:
      - network-id